// src/oracle.js — Gemini + Google Search
const { GoogleGenerativeAI } = require('@google/generative-ai');
const axios  = require('axios');
const db     = require('./db');
const logger = require('./logger');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const FEE   = 0.02;

// ВИПРАВЛЕННЯ 6: lazy ініціалізація моделей — не падає якщо ключ відсутній при імпорті
let _verifyModel  = null;
let _moderateModel = null;

function getVerifyModel() {
  if (!_verifyModel) {
      _verifyModel = genAI.getGenerativeModel({
            model: 'gemini-1.5-pro',
                  tools: [{ googleSearch: {} }],
                      });
                        }
                          return _verifyModel;
                          }

                          function getModerateModel() {
                            if (!_moderateModel) {
                                _moderateModel = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
                                  }
                                    return _moderateModel;
                                    }

                                    // ── CoinGecko ────────────────────────────
                                    async function verifyCrypto(market) {
                                      try {
                                          const coinMap = {
                                                bitcoin:'bitcoin', btc:'bitcoin',
                                                      ethereum:'ethereum', eth:'ethereum',
                                                            solana:'solana', sol:'solana',
                                                                  bnb:'binancecoin',
                                                                      };
                                                                          const q      = market.question.toLowerCase();
                                                                              const coinId = Object.entries(coinMap).find(([k]) => q.includes(k))?.[1];
                                                                                  if (!coinId) return null;

                                                                                      const priceMatch = market.question.match(/\$[\d,]+/);
                                                                                          if (!priceMatch) return null;
                                                                                              const target = parseFloat(priceMatch[0].replace(/[$,]/g, ''));

                                                                                                  const res = await axios.get('https://api.coingecko.com/api/v3/simple/price', {
                                                                                                        params: { ids: coinId, vs_currencies: 'usd' }, timeout: 8000,
                                                                                                            });
                                                                                                                const current = res.data[coinId]?.usd;
                                                                                                                    if (!current) return null;

                                                                                                                        let result = null;
                                                                                                                            if (q.match(/перевищить|перетне|досягне|above|exceed|вище/)) result = current > target ? 'yes' : 'no';
                                                                                                                                else if (q.match(/нижче|below|впаде/))                        result = current < target ? 'yes' : 'no';
                                                                                                                                    if (!result) return null;

                                                                                                                                        return {
                                                                                                                                              result, confidence: 98, method: 'api_crypto',
                                                                                                                                                    explanation: `${coinId}: $${current.toLocaleString()} | ціль $${target.toLocaleString()} → ${result.toUpperCase()}`,
                                                                                                                                                        };
                                                                                                                                                          } catch (err) {
                                                                                                                                                              logger.warn('CoinGecko:', err.message);
                                                                                                                                                                  return null;
                                                                                                                                                                    }
                                                                                                                                                                    }

                                                                                                                                                                    // ── ExchangeRate API ─────────────────────
                                                                                                                                                                    async function verifyForex(market) {
                                                                                                                                                                      try {
                                                                                                                                                                          const pairMatch = market.question.match(/([A-Z]{3})\/([A-Z]{3})/);
                                                                                                                                                                              if (!pairMatch) return null;
                                                                                                                                                                                  const [, base, quote] = pairMatch;
                                                                                                                                                                                      const targetMatch = market.question.match(/[\d.]+/);
                                                                                                                                                                                          if (!targetMatch) return null;
                                                                                                                                                                                              const target = parseFloat(targetMatch[0]);

                                                                                                                                                                                                  const res = await axios.get(`https://api.exchangerate-api.com/v4/latest/${base}`, { timeout: 8000 });
                                                                                                                                                                                                      const current = res.data.rates?.[quote];
                                                                                                                                                                                                          if (!current) return null;

                                                                                                                                                                                                              const q = market.question.toLowerCase();
                                                                                                                                                                                                                  let result = null;
                                                                                                                                                                                                                      if (q.match(/вище|above|перевищить/))   result = current > target ? 'yes' : 'no';
                                                                                                                                                                                                                          else if (q.match(/нижче|below|впаде/))  result = current < target ? 'yes' : 'no';
                                                                                                                                                                                                                              if (!result) return null;

                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                        result, confidence: 96, method: 'api_forex',
                                                                                                                                                                                                                                              explanation: `${base}/${quote}: ${current} | ціль ${target} → ${result.toUpperCase()}`,
                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                        logger.warn('Forex:', err.message);
                                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                              // ── Gemini + Google Search ────────────────
                                                                                                                                                                                                                                                              async function verifyWithGemini(market) {
                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                    const deadline = new Date(market.deadline).toLocaleDateString('uk-UA');
                                                                                                                                                                                                                                                                        const today    = new Date().toLocaleDateString('uk-UA');

                                                                                                                                                                                                                                                                            const prompt = `Ти — верифікатор prediction market. Використай Google Search.

                                                                                                                                                                                                                                                                            Питання: "${market.question}"
                                                                                                                                                                                                                                                                            Деталі: "${market.sub}"
                                                                                                                                                                                                                                                                            Дедлайн: ${deadline} | Сьогодні: ${today}
                                                                                                                                                                                                                                                                            Джерело: ${market.source || 'не вказано'}

                                                                                                                                                                                                                                                                            Відповідай ТІЛЬКИ валідним JSON:
                                                                                                                                                                                                                                                                            {"result":"yes","confidence":95,"explanation":"пояснення","source_used":"джерело"}

                                                                                                                                                                                                                                                                            Правила: result = yes|no|unclear. confidence < 70 → unclear. Дедлайн не настав → unclear.`;

                                                                                                                                                                                                                                                                                const res   = await getVerifyModel().generateContent(prompt);
                                                                                                                                                                                                                                                                                    const raw   = res.response.text().trim();
                                                                                                                                                                                                                                                                                        const match = raw.match(/\{[\s\S]*?\}/);
                                                                                                                                                                                                                                                                                            if (!match) throw new Error('Невалідний JSON від Gemini');

                                                                                                                                                                                                                                                                                                const p = JSON.parse(match[0]);
                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                          result: p.result, confidence: p.confidence || 0,
                                                                                                                                                                                                                                                                                                                explanation: p.explanation, source: p.source_used,
                                                                                                                                                                                                                                                                                                                      method: 'gemini_search',
                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                logger.error('Gemini verify:', err.message);
                                                                                                                                                                                                                                                                                                                                    return { result: 'unclear', confidence: 0, explanation: 'Помилка AI', method: 'error' };
                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                      // ── Модерація ринків гравців ──────────────
                                                                                                                                                                                                                                                                                                                                      async function moderateUserMarket(market) {
                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                            const prompt = `Модератор prediction market.
                                                                                                                                                                                                                                                                                                                                            Питання: "${market.question}"
                                                                                                                                                                                                                                                                                                                                            Деталі: "${market.sub || ''}"

                                                                                                                                                                                                                                                                                                                                            ✅ Дозволено: чітка YES/NO, публічно перевіряється, актуальне
                                                                                                                                                                                                                                                                                                                                            ❌ Заборонено: образи, приватні особи, непевірювані питання, спам

                                                                                                                                                                                                                                                                                                                                            Відповідай ТІЛЬКИ JSON:
                                                                                                                                                                                                                                                                                                                                            {"approved":true,"reason":"пояснення","suggestion":"порада"}`;

                                                                                                                                                                                                                                                                                                                                                const res   = await getModerateModel().generateContent(prompt);
                                                                                                                                                                                                                                                                                                                                                    const raw   = res.response.text().trim();
                                                                                                                                                                                                                                                                                                                                                        const match = raw.match(/\{[\s\S]*?\}/);
                                                                                                                                                                                                                                                                                                                                                            if (!match) return { approved: true, reason: 'Авто-схвалення' };
                                                                                                                                                                                                                                                                                                                                                                return JSON.parse(match[0]);
                                                                                                                                                                                                                                                                                                                                                                  } catch {
                                                                                                                                                                                                                                                                                                                                                                      return { approved: true, reason: 'AI недоступний' };
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        // ── Виплата переможцям ───────────────────
                                                                                                                                                                                                                                                                                                                                                                        function payoutWinners(market, result) {
                                                                                                                                                                                                                                                                                                                                                                          const bets = db.getBetsForMarket(market.id);

                                                                                                                                                                                                                                                                                                                                                                            // Повернення якщо одна сторона порожня
                                                                                                                                                                                                                                                                                                                                                                              if (market.poolYes === 0 || market.poolNo === 0) {
                                                                                                                                                                                                                                                                                                                                                                                  logger.info(`↩ #${market.id}: повернення (порожній пул)`);
                                                                                                                                                                                                                                                                                                                                                                                      bets.forEach(b => db.addGems(b.userId, b.amount));
                                                                                                                                                                                                                                                                                                                                                                                          db.updateMarket(market.id, { status:'resolved', result:'refund', resolvedAt: new Date().toISOString() });
                                                                                                                                                                                                                                                                                                                                                                                              return { type:'refund', total:0, winners:0, losers:0 };
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                  const totalPool   = market.poolYes + market.poolNo;
                                                                                                                                                                                                                                                                                                                                                                                                    const netPool     = totalPool * (1 - FEE);
                                                                                                                                                                                                                                                                                                                                                                                                      const winPool     = result === 'yes' ? market.poolYes : market.poolNo;
                                                                                                                                                                                                                                                                                                                                                                                                        const winningBets = bets.filter(b => b.side === result);
                                                                                                                                                                                                                                                                                                                                                                                                          let totalPayout   = 0;

                                                                                                                                                                                                                                                                                                                                                                                                            winningBets.forEach(bet => {
                                                                                                                                                                                                                                                                                                                                                                                                                const payout = Math.floor((bet.amount / winPool) * netPool);
                                                                                                                                                                                                                                                                                                                                                                                                                    db.addGems(bet.userId, payout);
                                                                                                                                                                                                                                                                                                                                                                                                                        // ВИПРАВЛЕННЯ 7: оновлюємо статистику гравця
                                                                                                                                                                                                                                                                                                                                                                                                                            const userData = db.load();
                                                                                                                                                                                                                                                                                                                                                                                                                                const uIdx = userData.users.findIndex(u => u.id === bet.userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (uIdx !== -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          userData.users[uIdx].wins++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                userData.users[uIdx].totalBets++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      db.save(userData);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalPayout += payout;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  logger.info(`💰 Гравець #${bet.userId}: +${payout} 💎`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Оновлюємо статистику програшів
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bets.filter(b => b.side !== result).forEach(bet => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const userData = db.load();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const uIdx = userData.users.findIndex(u => u.id === bet.userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (uIdx !== -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          userData.users[uIdx].losses++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                userData.users[uIdx].totalBets++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      db.save(userData);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              db.updateMarket(market.id, { status:'resolved', result, resolvedAt: new Date().toISOString() });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type: 'payout', total: totalPayout,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        winners: winningBets.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            losers:  bets.length - winningBets.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ── Перевірка закінчених ринків ──────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              async function checkExpiredMarkets() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const expired = db.getExpiredMarkets();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!expired.length) return [];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logger.info(`🔍 Перевіряю ${expired.length} ринків...`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const resolved = [];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (const market of expired) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.info(`⏳ #${market.id}: ${market.question}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db.updateMarket(market.id, { status: 'checking' });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let v = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (market.room === 'crypto')                       v = await verifyCrypto(market);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!v && ['global','eu'].includes(market.room))    v = await verifyForex(market);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!v)                                             v = await verifyWithGemini(market);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  logger.info(`📊 #${market.id}: ${v.result} (${v.confidence}%)`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (v.result !== 'unclear' && v.confidence >= 75) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const payout = payoutWinners(market, v.result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db.updateMarket(market.id, { resolveNote: `${v.explanation} [${v.method}]` });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                resolved.push({ market, verification: v, payout });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.info(`✅ #${market.id}: ${v.result} | виплачено ${payout.total} 💎`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      db.updateMarket(market.id, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status: 'pending_review',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          resolveNote: `Gemini невпевнений (${v.confidence}%): ${v.explanation}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          logger.warn(`⚠️ #${market.id} → ручна перевірка`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Сповіщаємо адміна
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { notifyMarketResolved } = require('./bot');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          db.updateMarket(market.id, { status: 'open' }); // повертаємо назад
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.error(`❌ #${market.id}:`, err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return resolved;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        module.exports = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          checkExpiredMarkets,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            moderateUserMarket,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              payoutWinners,       // ВИПРАВЛЕННЯ 8: експортуємо — потрібно в bot.js
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                verifyCrypto,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  verifyForex,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    verifyWithGemini,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    